use_frameworks!
platform :ios, '8.0'

target 'Segundo_Example', :exclusive => true do
  pod "Segundo", :path => "../"
end

target 'Segundo_Tests', :exclusive => true do
  pod "Segundo", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
