source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Segundo_Example', :exclusive => true do
  pod "Segundo", :path => "../"
end

target 'Segundo_Tests', :exclusive => true do
  pod "Segundo", :path => "../"

  pod 'DynamicInvoker', :git => 'https://github.com/MediaHound/DyanmicInvoker.git'

  pod 'Specta'
  pod 'Expecta'
end
